apiVersion: v1
kind: Secret
metadata:
  name: gitlab-pull-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5naXRsYWIuY29tIjp7ImF1dGgiOiJWR2xoZVc5ek9tZHNjR0YwTFhGYVUzWkllVUV4UlRGVFlVY3pXVkZHWnpWMiJ9fX0=
---
apiVersion: v1
kind: Service
metadata:
  name: sgadnxtui
  labels:
    app: sgadnxtui
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: sgadnxtui
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sgadnxtui
  labels:
    app: sgadnxtui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sgadnxtui
  template:
    metadata:
      labels:
        app: sgadnxtui
    spec:
      containers:
        - name: sgadnxtui
          image: registry.gitlab.com/ups-dev/development/gitlab/packages/docker:sgadui-nxt-dev-1.0.3
          ports:
            - containerPort: 8080
          env:
            - name: NITRO_PORT
              value: "8080"
            - name: PORT
              value: "443"
            - name: KEYCLOAK_ISSUER
              value: "https://auth.ups.edu.ec/realms/dev"
            - name: KEYCLOAK_ID
              value: "dev-sgadui"
            - name: KEYCLOAK_SECRET
              value: "fH4mALTkm3kJqjIRM99fPykjTsH5BDKY"
            - name: AUTH_ORIGIN
              value: "https://sgadui.ups.edu.ec/"
            - name: AUTH_SECRET
              value: "12345"
            - name: NEXTAUTH_URL
              value: "https://sgadui.ups.edu.ec/"
      imagePullSecrets:
        - name: gitlab-pull-secret
      nodeSelector:
        kubernetes.io/hostname: clkbrnts-02